[package]
name = "arcturus"
version = "0.1.0"
authors = ["abhi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
async-std = {version ="1.5.0", features=["attributes"]}
clap = "2.33.0"
either = "1.5.3"
